name: "Deploy Bot"
description: "Build & Publish bot to your environment"

inputs:
  ENVIRONMENT:
    description:  env where bot will be deployed
    required: true
    default: qa-int
  BOT_SRC_DIR:
    description: "Directory where the bot src is"
    required: true
  BOT_NAME:
    description: "Name of the bot"
    required: true
  USERNAME:
    description: "Name of the user admin that will deploy the bot"
    required: true
  PASSWORD:
    description: "Password of the user admin that will deploy the bot"
    required: true
  BUILD_COMMAND:
    description: "The command that builds the bot, for example 'npm run build'"
    required: true
    default: "npm run build"
  SLACK_WEBHOOK_URL:
    description: "Slack's webhook"
    required: false
    
runs:
  using: "composite"
  steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Setting up cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Botonic
        working-directory: ${{ inputs.BOT_SRC_DIR }}
        run: npm install -g @botonic/cli
        shell: bash

      - name: Botonic version
        working-directory: ${{ inputs.BOT_SRC_DIR }}
        run: botonic --version
        shell: bash

      - name: Install Dependencies
        working-directory: ${{ inputs.BOT_SRC_DIR }}
        run: npm ci
        shell: bash

      - name: Deploy Bot
        working-directory: ${{ inputs.BOT_SRC_DIR }}
        run: botonic deploy -b ${{ inputs.BOT_NAME }} -c ${{ inputs.BUILD_COMMAND }} -e ${{ inputs.USERNAME }} -p ${{ inputs.PASSWORD }}
        shell: bash

      - name: Send Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
            "icon_emoji": ":rocket:",
            "channel": "logging-${{inputs.ENVIRONMENT}}" ,
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Botaso deployed!"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Try Botaso",
                    "emoji": true
                  },
                  "value": "try_botaso",
                  "url": "https://botaso-staging.netlify.app/",
                  "action_id": "button-action"
                }
              }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
